#!/usr/bin/env python3
# 把 Noto Sans SC 各字重按 Unicode 切成小片（unicode-range 分包），
# 保持完全相同的字体外观（font-family / font-weight / font-display 不变），
# 浏览器按需只下载页面用到的字所在的分片。
import io
import os
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options

SRC_DIR = "node_modules/@fontsource/noto-sans-sc/files"
WEIGHTS = [400, 500, 600, 700]
OUT_WOFF2_DIR = "public/fonts/nssc"
OUT_CSS = "app/noto-sans-sc-sliced.css"
URL_PREFIX = "/fonts/nssc/"
CHUNK_SIZE = 500  # 每片字符数


def fmt_unicode_range(cps):
    lo, hi = cps[0], cps[-1]
    return f"U+{lo:04X}" if lo == hi else f"U+{lo:04X}-{hi:04X}"


def slice_weight(weight, css_lines):
    src = os.path.join(SRC_DIR, f"noto-sans-sc-chinese-simplified-{weight}-normal.woff2")
    with open(src, "rb") as f:
        raw = f.read()
    base = TTFont(io.BytesIO(raw))
    cps = sorted(base.getBestCmap().keys())
    base.close()

    count = 0
    for start in range(0, len(cps), CHUNK_SIZE):
        window = cps[start:start + CHUNK_SIZE]
        font = TTFont(io.BytesIO(raw))
        opts = Options()
        opts.flavor = "woff2"
        opts.layout_features = ["*"]   # 保留全部排版特性，渲染不变
        opts.name_IDs = ["*"]
        opts.notdef_outline = True
        opts.recalc_timestamp = False
        ss = Subsetter(options=opts)
        ss.populate(unicodes=window)
        ss.subset(font)
        fname = f"nssc-{weight}-{count}.woff2"
        font.save(os.path.join(OUT_WOFF2_DIR, fname))
        font.close()
        css_lines.append(
            "@font-face{font-family:'Noto Sans SC';font-style:normal;font-weight:%d;"
            "font-display:swap;src:url('%s%s') format('woff2');unicode-range:%s;}"
            % (weight, URL_PREFIX, fname, fmt_unicode_range(window))
        )
        count += 1
    print(f"  weight {weight}: {count} chunks from {len(cps)} glyphs")
    return count


def main():
    os.makedirs(OUT_WOFF2_DIR, exist_ok=True)
    css_lines = ["/* Noto Sans SC — sliced (auto-generated by scripts/slice-cjk-font.py). 同款字体，按需分片加载。 */"]
    total = 0
    for w in WEIGHTS:
        total += slice_weight(w, css_lines)
    with open(OUT_CSS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(css_lines) + "\n")
    print(f"DONE: {total} chunks total -> {OUT_WOFF2_DIR}")
    print(f"CSS  -> {OUT_CSS} ({len(css_lines)-1} @font-face rules)")


if __name__ == "__main__":
    main()
